[build-system]
requires = [
    "setuptools>=42",
    "cmake>=3.22",
    "oldest-supported-numpy",
    "scikit-build>=0.14.1",
]

build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
